AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Building an inline AI agent to test remote MCP servers

Parameters:
  OpenAIKey:
    Type: String
    NoEcho: true
  ConnectionString:
    Type: String
    NoEcho: true

Metadata:
  esbuild-properties: &esbuild-properties
    Format: esm
    Minify: true
    OutExtension:
      - .js=.mjs
    Target: es2020
    Sourcemap: false
    EntryPoints:
      - index.mjs
    Banner:
      - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
    External:
      - '@aws-sdk/*'

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 30
    MemorySize: 1024
    CodeUri: functions
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  MCPTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

  AgentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - agent.mjs
    Properties:
      Handler: agent.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !GetAtt MCPTable.Arn
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          TABLE_NAME: !Ref MCPTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /agent
            Method: POST

  SaveServerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - save-server.mjs
    Properties:
      Handler: save-server.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt MCPTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MCPTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /servers
            Method: POST

  DeleteServerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - delete-server.mjs
    Properties:
      Handler: delete-server.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:DeleteItem
              Resource: !GetAtt MCPTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MCPTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /servers/{id}
            Method: DELETE

  ConfigureFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - configure.mjs
    Properties:
      Handler: configure.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !GetAtt MCPTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MCPTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /servers
            Method: GET

  ApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - api.mjs
    Properties:
      Handler: api.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          CONNECTION_STRING: !Ref ConnectionString

Outputs:
  HttpApiUrl:
    Description: The HTTP API endpoint for testing the agent
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/agent'
  ApiUrl:
    Description: The API endpoint for the garden API
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
