openapi: 3.0.3
info:
  title: Farm Animal Tracker API
  description: API for managing core animal data on a farm
  version: 1.0.0
tags:
  - name: Animal Registry
    description: Core animal tracking and lineage
  - name: Animal Care
    description: Management of animal care, like treatment and weight tracking
  - name: Locations
    description: Management of farm locations
paths:
  /animals:
    post:
      summary: Register a new animal
      operationId: add-animal
      tags: [Animal Registry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalInput'
      responses:
        '201':
          $ref: "#/components/responses/Created"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"
    get:
      summary: List animals with optional filters
      operationId: list-animals
      tags: [Animal Registry]
      parameters:
        - name: species
          in: query
          description: Filter by species
          required: false
          schema:
            type: string
          example:
            chicken
      responses:
        '200':
          description: A list of animals
          content:
            text/plain:
              schema:
                type: string

  /animals/{name}:
    parameters:
      - $ref: "#/components/parameters/AnimalName"
    get:
      summary: Get animal details by name
      operationId: get-animal-by-name
      tags: [Animal Registry]
      responses:
        '200':
          description: Animal was found and details were returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnimalDetail"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    put:
      summary: Update animal status or notes by name
      tags: [Animal Registry]
      operationId: update-animal-status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_active:
                  type: boolean
                notes:
                  type: string
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"

  /animals/{name}/lineage:
    parameters:
      - $ref: "#/components/parameters/AnimalName"
    put:
      summary: Adds or updates animal lineage
      operationId: log-lineage
      tags: [Animal Registry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Lineage"
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    get:
      summary: Get animal lineage
      operationId: get-lineage-by-animal-name
      tags: [Animal Registry]
      responses:
        '200':
          description: The lineage was found and returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lineage"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"

  /animals/{name}/weights:
    parameters:
      - $ref: "#/components/parameters/AnimalName"
    post:
      summary: Adds a new weight for animal
      operationId: log-weight
      tags: [Animal Care]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Weight"
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    get:
      summary: Gets a list of all recorded weights for an animal
      operationId: list-weights-by-name
      tags: [Animal Care]
      responses:
        '200':
          description: The animal was found and a list of weights was returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  weights:
                    type: array
                    items:
                      $ref: "#/components/schemas/Weight"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"

  /animals/{name}/treatments:
    parameters:
      - $ref: "#/components/parameters/AnimalName"
    post:
      summary: Add a treatment for an animal
      operationId: log-treatment
      tags: [Animal Care]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Treatment"
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    get:
      summary: List all treatments for an animal
      operationId: list-treatments-by-animal-name
      tags: [Animal Care]
      responses:
        '200':
          description: The animal was found and the list of treatments was returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  treatments:
                    type: array
                    items:
                      $ref: "#/components/schemas/Treatment"
                required:
                  - treatments

  /weights:
    get:
      summary: List current weight of all active animals
      operationId: list-weights
      tags: [Animal Care]
      responses:
        '200':
          description: The list of current animals weights was returned
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    - $ref: "#/components/schemas/Weight"
        '500':
          $ref: "#/components/responses/ServerError"

  /treatments:
    get:
      summary: Lists treatments for all active animals
      operationId: list-treatments
      tags: [Animal Care]
      responses:
        '200':
          description: The list of animal treatments was returned
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    - $ref: "#/components/schemas/Treatment"
        '500':
          $ref: "#/components/responses/ServerError"

  /locations:
    post:
      summary: Add a new location for farm animals
      operationId: add-location
      tags: [Location]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        '201':
          $ref: "#/components/responses/Created"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"
    get:
      summary: List all locations
      operationId: list-locations
      tags: [Location]
      responses:
        '200':
          description: A list of locations was returned
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/SystemFields"
                    - $ref: "#/components/schemas/Location"
        '500':
          $ref: "#/components/responses/ServerError"

  /locations/{locationName}:
    parameters:
      - $ref: "#/components/parameters/LocationName"
    get:
      summary: Get information about a location
      operationId: get-location
      tags: [Location]
      responses:
        '200':
          description: The location was found and details were returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    put:
      summary: Update name or notes for a location
      operationId: update-location
      tags: [Location]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                notes:
                  type: string
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
    delete:
      summary: Remove a location
      operationId: remove-location
      tags: [Location]
      responses:
        '204':
          $ref: "#/components/responses/NoContent"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    AnimalInput:
      type: object
      required: [name, species]
      properties:
        name:
          type: string
        species:
          type: string
        breed:
          type: string
        sex:
          type: string
          enum: [male, female, unknown]
        date_of_birth:
          type: string
        date_acquired:
          type: string
        is_active:
          type: boolean
        tag_number:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true

    AnimalDetail:
      allOf:
        - $ref: "#/components/schemas/AnimalInput"
        - $ref: "#/components/schemas/SystemFields"

    SystemFields:
      type: object
      properties:
        id:
          type: string
      required:
        - id

    Lineage:
      type: object
      properties:
        mother_id:
          type: string
        father_id:
          type: string

    Weight:
      type: object
      properties:
        measured_on:
          type: string
          format: date
        measured_by:
          type: string
        weight_kg:
          type: number
      required:
        - measured_on
        - weight_kg

    Treatment:
      type: object
      properties:
        treatment_type:
          type: string
        product_used:
          type: string
        dosage:
          type: string
        administered_on:
          type: string
          format: date
        administered_by:
          type: string
        notes:
          type: string
      required:
        - treatment_type
        - administered_on

    Location:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        notes:
          type: string
      required:
        - name

  responses:
    Created:
      description: The entity was successfully created
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
            required:
              - id
    BadRequest:
      description: The request was malformed or unexpected
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    NotFound:
      description: The requested entity could not be found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    ServerError:
      description: Something went wrong while processing the request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    NoContent:
      description: The operation succeeded and there is no data to return

  parameters:
    AnimalName:
      name: name
      in: path
      description: Name of an animal (case insensitive)
      required: true
      schema:
        type: string
      example:
        daisy

    LocationName:
      name: locationName
      in: path
      description: Name of a location
      required: true
      schema:
        type: string
